Added SwingingBlade
Terasology/AdventureAssets pull request #2
Opened 2017-06-03 15:18 UTC by nihal111

Adds the swinging blade (a crude model) with a test structural template.

### Steps to test
1. Console: `give toolbox`
2. Select toolbox and rightclick
3. Select "Structure Template Spawner" -> "AdventureAssets:bladeRoom" -> Give Item
4. Select the Structure Spawner from inventory and right click nearby to spawn it.

Enter the room and witness the gigantic swingingBlade.

2017-06-08 14:20 UTC, flo requested changes

2017-06-08 14:20 UTC, flo commented on src/main/java/org/terasology/adventureassets/traps/swingingblade/SpawnSwingingBladeServerSystem.java
> +            entityBuilder.build();
In neither prefab nor during the construction i see any persistence flag setting

2017-06-08 14:20 UTC, flo commented on src/main/java/org/terasology/adventureassets/traps/swingingblade/SwingingBladeClientSystem.java
> +        Prefab swingingBladePrefab = CoreRegistry.get(AssetManager.class).getAsset("AdventureAssets:swingingBladeMesh", Prefab.class).get();
Asset manager schould be obtained via dependency injection

2017-06-08 14:20 UTC, flo commented on src/main/java/org/terasology/adventureassets/traps/swingingblade/SwingingBladeClientSystem.java
> +                float t = CoreRegistry.get(Time.class).getGameTime();
Time should b obtained via dependenxy inkection like anything else ibtained currently from CoreRegistry

2017-06-08 14:20 UTC, flo commented on src/main/java/org/terasology/adventureassets/traps/swingingblade/SwingingBladeComponent.java
> +    /* Time taken by the swinging blade to complete one two and fro motion (in seconds)*/
A star is missing to make it a javadoc

2017-06-08 14:20 UTC, flo commented on src/main/java/org/terasology/adventureassets/traps/swingingblade/SwingingBladeServerSystem.java
> +                float T = swingingBladeComponent.timePeriod;
Identifiers of variables should be lower case

2017-06-09 16:46 UTC, nihal111 commented on src/main/java/org/terasology/adventureassets/traps/swingingblade/SpawnSwingingBladeServerSystem.java
> +            entityBuilder.build();
Fixed.

2017-06-09 17:22 UTC, flo requested changes

2017-06-09 17:22 UTC, flo commented on src/main/java/org/terasology/adventureassets/traps/TrapPlaceholderSystem.java
> +    public void onBuildTemplateStringWithBlockRegions(BuildStructureTemplateStringEvent event, EntityRef template,
Method name is wrong

2017-06-09 17:26 UTC, merged

2017-06-09 17:26 UTC, nihal111 commented on src/main/java/org/terasology/adventureassets/traps/TrapPlaceholderSystem.java
> +    public void onBuildTemplateStringWithBlockRegions(BuildStructureTemplateStringEvent event, EntityRef template,
Fixed.